const VERSION="V2.0",PRACTICE=10,TEST=5;
const lessons={english:{title:"🇬🇧 TO BE & construction de phrases",theory:`<div class="muted">ÉTAPE 1 · RAPPEL</div><h2>Construire une phrase avec TO BE</h2><p><b>I am</b> · <b>he/she/it is</b> · <b>you/we/they are</b>.</p><p>À la forme négative : <i>She is not / She isn't.</i><br>Question : <i>Are they ready?</i></p><p>Ne regarde pas seulement le nom : remplace mentalement le sujet par un pronom.</p><button id="listen">🔊 Écouter les exemples</button><br><br><button id="practice" class="primary">Commencer l'entraînement →</button>`,q:[
{t:"My parents ___ already at the station.",a:["am","is","are"],c:2,e:"My parents = they → are."},{t:"Neither Tom nor his sister ___ at school today.",a:["am","is","are"],c:1,e:"Le sujet le plus proche, his sister, est singulier → is."},{t:"Complete : I ___ not afraid of difficult exercises.",type:"text",accept:["am"],e:"Avec I, le verbe to be est am."},{t:"Put in the negative: She is ready.",type:"text",accept:["she is not ready","she isn't ready","she is not ready." ,"she isn't ready."],e:"She is ready → She is not / isn't ready."},{t:"Choose the correct question.",a:["Are your friends ready?","Is your friends ready?","Do your friends are ready?"],c:0,e:"Your friends = they → Are they…?"},{t:"Complete : Where ___ your new English books?",type:"text",accept:["are"],e:"Books est pluriel → are."},{t:"Translate: « Nous ne sommes pas en retard. »",type:"text",accept:["we are not late","we aren't late","we are not late.","we aren't late."],e:"We → are ; négation → are not / aren't."},{t:"My brother and I ___ responsible for dinner tonight.",a:["am","is","are"],c:2,e:"My brother and I = we → are."},{t:"Correct the sentence: They is very tired.",type:"text",accept:["they are very tired","they are very tired."],e:"They exige are."},{t:"___ it true that your cousins are from London?",a:["Am","Is","Are"],c:1,e:"It est singulier → Is it…?"},
{t:"TEST · Translate: « Est-ce que tes parents sont à la maison ? »",type:"text",accept:["are your parents at home","are your parents at home?"],e:"Question avec parents = they → Are your parents…?"},{t:"TEST · The news ___ surprising.",a:["am","is","are"],c:1,e:"News se traite ici comme singulier → is."},{t:"TEST · Correct: Is they your classmates?",type:"text",accept:["are they your classmates","are they your classmates?"],e:"They → are."},{t:"TEST · Sarah and Louise ___ not available, but Tom ___ here.",type:"text",accept:["are is","are, is"],e:"Sarah and Louise = they → are ; Tom = he → is."},{t:"TEST · Choose the fully correct sentence.",a:["My friends is not here.","My friends aren't here.","My friends doesn't be here."],c:1,e:"Friends = they → are / aren't."}]},
math:{title:"➗ Entiers & priorités",theory:`<div class="muted">ÉTAPE 1 · RAPPEL</div><h2>Signes et priorités</h2><p>Ordre : <b>parenthèses → puissances → × et ÷ → + et −</b>.</p><p>Pour × et ÷ : mêmes signes → positif ; signes différents → négatif.</p><p>Exemple : <b>−3 + 4² × (−2) = −3 + 16 × (−2) = −35</b>.</p><button id="practice" class="primary">Commencer l'entraînement →</button>`,q:[
{t:"−7 + 12 − 9 =",type:"text",accept:["-4","−4"],e:"−7 + 12 = 5 ; 5 − 9 = −4."},{t:"(−4) × (−6) × (−2) =",a:["−48","48","−12"],c:0,e:"Deux négatifs donnent +24, puis × −2 = −48."},{t:"18 ÷ (−3) + 7 =",type:"text",accept:["1"],e:"18 ÷ −3 = −6 ; −6 + 7 = 1."},{t:"−3 + 4² × 2 =",type:"text",accept:["29"],e:"Puissance d'abord : 4²=16, puis ×2=32, puis −3 → 29."},{t:"5 − [3 × (−4)] =",a:["−7","17","−17"],c:1,e:"3×−4=−12 ; 5−(−12)=17."},{t:"(−2)³ + 10 =",type:"text",accept:["2"],e:"(−2)³=−8 ; −8+10=2."},{t:"−24 ÷ (−6) × (−3) =",type:"text",accept:["-12","−12"],e:"−24÷−6=4 ; 4×−3=−12."},{t:"Quel calcul vaut −14 ?",a:["−2 × 7","2 × 7","−7 − (−7)"],c:0,e:"−2×7 = −14."},{t:"6 + 2 × (−5) − 3 =",type:"text",accept:["-7","−7"],e:"2×−5=−10 ; 6−10−3=−7."},{t:"|−18| − |−5| =",type:"text",accept:["13"],e:"18−5=13."},
{t:"TEST · −5² + 3 × 4 =",type:"text",accept:["-13","−13"],e:"Sans parenthèses, −5²=−25 ; puis +12 = −13."},{t:"TEST · (−5)² + 3 × (−4) =",type:"text",accept:["13"],e:"25−12=13."},{t:"TEST · 30 ÷ [2 × (−3)] + 9 =",type:"text",accept:["4"],e:"2×−3=−6 ; 30÷−6=−5 ; +9=4."},{t:"TEST · Quel est le plus grand ?",a:["−3²","(−3)²","−(3²)"],c:1,e:"(−3)²=9, les deux autres valent −9."},{t:"TEST · −2 × [4 − (−3)] + 5 =",type:"text",accept:["-9","−9"],e:"4−(−3)=7 ; −2×7=−14 ; +5=−9."}]}};
let S=JSON.parse(localStorage.getItem("eliseLearningV2")||'{"xp":0,"streak":0,"lastDay":null,"sessions":[]}'),lesson,i,pc,tc,start,theoryStart,theorySec,locked,currentRec,diff="",enjoy="";const $=x=>document.getElementById(x),norm=x=>x.trim().toLowerCase().replace(/’/g,"'").replace(/\s+/g," ");
function show(x){document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));$(x).classList.add("active");render();scrollTo(0,0)}
async function report(event,details){try{await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({"form-name":"learning-report",event,details})})}catch(e){console.log("report",e)}}
function begin(k){lesson=lessons[k];i=pc=tc=0;start=theoryStart=Date.now();$("title").textContent=lesson.title;$("theory").innerHTML=lesson.theory;$("theory").hidden=false;$("quiz").hidden=true;$("bar").style.width="8%";show("lesson");$("practice").onclick=startQuiz;if($("listen"))$("listen").onclick=()=>{let u=new SpeechSynthesisUtterance("I am ready. She isn't late. Are they at home? We are at school.");u.lang="en-GB";speechSynthesis.speak(u)}}
function startQuiz(){theorySec=Math.round((Date.now()-theoryStart)/1000);$("theory").hidden=true;$("quiz").hidden=false;question()}
function question(){locked=false;let q=lesson.q[i];$("phase").textContent=i<PRACTICE?`ÉTAPE 2 · ENTRAÎNEMENT ${i+1}/${PRACTICE}`:`ÉTAPE 3 · MINI-TEST ${i-PRACTICE+1}/${TEST}`;$("question").textContent=q.t;$("answers").innerHTML="";$("feedback").innerHTML="";$("feedback").className="";$("next").hidden=true;if(q.type==="text"){let input=document.createElement("input");input.className="answerInput";input.placeholder="Écris ta réponse…";input.autocapitalize="none";input.onkeydown=e=>{if(e.key==="Enter")checkText(input)};$("answers").appendChild(input);let b=document.createElement("button");b.className="primary";b.textContent="Valider";b.onclick=()=>checkText(input);$("answers").appendChild(b);setTimeout(()=>input.focus(),100)}else q.a.forEach((a,n)=>{let b=document.createElement("button");b.className="choice";b.textContent=a;b.onclick=()=>answer(n,b);$("answers").appendChild(b)});$("bar").style.width=(12+i*(84/(PRACTICE+TEST)))+"%"}
function mark(ok,explain){if(ok){i<PRACTICE?pc++:tc++}$("feedback").className="feedback "+(ok?"ok":"no");$("feedback").innerHTML=(ok?"🎯 <b>Exact !</b> ":"💡 <b>À retenir :</b> ")+explain;$("next").hidden=false}
function answer(n,b){if(locked)return;locked=true;let q=lesson.q[i],ok=n===q.c;b.classList.add(ok?"good":"bad");if(!ok)$("answers").children[q.c].classList.add("good");mark(ok,q.e)}
function checkText(input){if(locked)return;locked=true;let q=lesson.q[i],ok=q.accept.map(norm).includes(norm(input.value));input.style.borderColor=ok?"#15966a":"#d94f4f";mark(ok,q.e+(ok?"":" Réponse attendue : "+q.accept[0]+"."))}
function next(){i++;i>=lesson.q.length?done():question()}
function done(){let total=Math.round((Date.now()-start)/1000),p=Math.round(tc/TEST*100),gain=(pc+tc)*10+(p>=80?50:0),today=new Date().toISOString().slice(0,10);S.xp+=gain;if(S.lastDay!==today){if(S.lastDay){let d=(new Date(today)-new Date(S.lastDay))/86400000;S.streak=d<=2?S.streak+1:1}else S.streak=1;S.lastDay=today}currentRec={date:new Date().toLocaleString("fr-BE"),title:lesson.title,theory:theorySec,practice:pc+"/"+PRACTICE,test:tc+"/"+TEST,pct:p,total,feedback:null};S.sessions.unshift(currentRec);save();$("pct").textContent=p+"%";$("badge").textContent=p>=80?"🏆":p>=65?"👍":"🌱";$("message").textContent=p>=80?"Maîtrisé ! Beau travail.":p>=65?"Réussi, à consolider.":"À retravailler : cette notion reviendra.";$("rTheory").textContent=fmt(theorySec);$("rPractice").textContent=pc+"/"+PRACTICE;$("rTest").textContent=tc+"/"+TEST+" ("+p+"%)";$("rTotal").textContent=fmt(total);diff=enjoy="";document.querySelectorAll(".emojiRow button").forEach(b=>b.classList.remove("selected"));$("comment").value="";report("Séance terminée",`${VERSION} | ${currentRec.title} | théorie ${fmt(theorySec)} | exercices ${currentRec.practice} | test ${currentRec.test} (${p}%) | total ${fmt(total)}`);show("result")}
function save(){localStorage.setItem("eliseLearningV2",JSON.stringify(S))}function fmt(s){return Math.floor(s/60)+" min "+String(s%60).padStart(2,"0")+" s"}
function render(){$("xp").textContent="⭐ "+S.xp+" XP";$("streak").textContent=S.streak;$("sessions").textContent=S.sessions.length;$("pxp").textContent=S.xp;$("time").textContent=Math.round(S.sessions.reduce((a,b)=>a+b.total,0)/60)+" min";let x=S.sessions[0];$("last").innerHTML=x?`<b>${x.title}</b><div class="muted">${x.date}</div><div class="row"><span>Théorie</span><b>${fmt(x.theory)}</b></div><div class="row"><span>Exercices</span><b>${x.practice}</b></div><div class="row"><span>Test</span><b>${x.test} · ${x.pct}%</b></div><div class="row"><span>Total</span><b>${fmt(x.total)}</b></div>${x.feedback?`<p><b>Feedback :</b> ${x.feedback.difficulty} ${x.feedback.enjoy}<br>${x.feedback.comment||""}</p>`:""}`:"Aucune séance."}
document.querySelectorAll("[data-start]").forEach(b=>b.onclick=()=>begin(b.dataset.start));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));$("back").onclick=()=>show("home");$("next").onclick=next;$("finish")?.addEventListener("click",()=>show("home"));document.querySelectorAll("#difficulty button").forEach(b=>b.onclick=()=>{diff=b.dataset.v;document.querySelectorAll("#difficulty button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});document.querySelectorAll("#enjoy button").forEach(b=>b.onclick=()=>{enjoy=b.dataset.v;document.querySelectorAll("#enjoy button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("sendFeedback").onclick=()=>{let comment=$("comment").value.trim();if(!diff||!enjoy){alert("Choisis la difficulté et si tu as aimé la séance 🙂");return}currentRec.feedback={difficulty:diff,enjoy,comment};save();report("Feedback d'Elise",`${VERSION} | ${currentRec.title} | test ${currentRec.pct}% | difficulté: ${diff} | appréciation: ${enjoy} | message: ${comment||"(aucun)"}`);$("sendFeedback").textContent="Feedback envoyé ✓";setTimeout(()=>show("home"),700)};render();report("Application ouverte",`${VERSION} | Elise Learning ouvert le ${new Date().toLocaleString("fr-BE")}`);
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});