const lessons={
english:{title:"🇬🇧 AM / IS / ARE",theory:`<div class="muted">ÉTAPE 1 · RAPPEL</div><h2>Le verbe TO BE</h2><p><b>I → am</b><br><b>he / she / it → is</b><br><b>you / we / they → are</b></p><p>Astuce : <b>my parents</b> = <b>they</b>, donc <i>My parents are…</i></p><button id="listen">🔊 Écouter</button><br><br><button id="practice" class="primary">J'ai compris →</button>`,q:[
["My parents ___ at home.",["am","is","are"],2,"My parents = they → They are."],["I ___ twelve years old.",["am","is","are"],0,"Avec I : am."],["Louise ___ my friend.",["am","is","are"],1,"Louise = she → is."],["We ___ at school.",["am","is","are"],2,"Avec we : are."],["My dog ___ big.",["am","is","are"],1,"My dog = it → is."],["They ___ best friends.",["am","is","are"],2,"Avec they : are."],["Tom ___ not at home.",["am","is","are"],1,"Tom = he → is."],["You ___ funny.",["am","is","are"],2,"Avec you : are."]]},
math:{title:"➗ Les entiers relatifs",theory:`<div class="muted">ÉTAPE 1 · RAPPEL</div><h2>Positifs et négatifs</h2><p>L'<b>opposé</b> est à la même distance de 0, de l'autre côté.</p><p><b>Opposé de −3 = 3</b><br><b>|−18| = 18</b></p><p>Parmi deux nombres négatifs, le plus proche de 0 est le plus grand.</p><button id="practice" class="primary">J'ai compris →</button>`,q:[
["L'opposé de −3 est…",["−3","3","0"],1,"On change le signe."],["|−18| vaut…",["−18","18","0"],1,"C'est la distance à 0."],["Le plus grand ?",["−12","−4","égaux"],1,"−4 est plus proche de 0."],["−5 + (−4) =",["−9","9","−1"],0,"−5 − 4 = −9."],["−4 × 5 =",["20","−20","−9"],1,"Négatif × positif = négatif."],["|−10| ___ 10",["<",">","="],2,"Les deux valent 10."],["−13 + 4 =",["−17","−9","9"],1,"On avance de 4 vers 0."],["(−4) × (−6) =",["−24","24","10"],1,"Négatif × négatif = positif."]]}}
let S=JSON.parse(localStorage.getItem("eliseLearning")||'{"xp":0,"streak":0,"lastDay":null,"sessions":[]}'),lesson,i,pc,tc,start,theoryStart,theorySec,locked;
const $=x=>document.getElementById(x);
function show(x){document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));$(x).classList.add("active");render();scrollTo(0,0)}
function begin(k){lesson=lessons[k];i=pc=tc=0;start=theoryStart=Date.now();$("title").textContent=lesson.title;$("theory").innerHTML=lesson.theory;$("theory").hidden=false;$("quiz").hidden=true;$("bar").style.width="10%";show("lesson");$("practice").onclick=startQuiz;if($("listen"))$("listen").onclick=()=>{let u=new SpeechSynthesisUtterance("I am. You are. He is. She is. We are. They are.");u.lang="en-GB";speechSynthesis.speak(u)}}
function startQuiz(){theorySec=Math.round((Date.now()-theoryStart)/1000);$("theory").hidden=true;$("quiz").hidden=false;question()}
function question(){locked=false;let q=lesson.q[i];$("phase").textContent=i<5?"ÉTAPE 2 · ENTRAÎNEMENT":"ÉTAPE 3 · MINI-TEST";$("question").textContent=q[0];$("answers").innerHTML="";$("feedback").innerHTML="";$("next").hidden=true;q[1].forEach((a,n)=>{let b=document.createElement("button");b.className="choice";b.textContent=a;b.onclick=()=>answer(n,b);$("answers").appendChild(b)});$("bar").style.width=(25+i*9)+"%"}
function answer(n,b){if(locked)return;locked=true;let q=lesson.q[i],ok=n===q[2];if(ok){b.classList.add("good");i<5?pc++:tc++}else{b.classList.add("bad");$("answers").children[q[2]].classList.add("good")}$("feedback").className="feedback "+(ok?"ok":"no");$("feedback").innerHTML=(ok?"🎯 <b>Exact !</b> ":"💡 <b>À retenir :</b> ")+q[3];$("next").hidden=false}
function next(){i++;i>=lesson.q.length?done():question()}
function done(){let total=Math.round((Date.now()-start)/1000),p=Math.round(tc/3*100),gain=(pc+tc)*10+(p>=80?30:0),today=new Date().toISOString().slice(0,10);S.xp+=gain;if(S.lastDay!==today){if(S.lastDay){let d=(new Date(today)-new Date(S.lastDay))/86400000;S.streak=d<=2?S.streak+1:1}else S.streak=1;S.lastDay=today}S.sessions.unshift({date:new Date().toLocaleString("fr-BE"),title:lesson.title,theory:theorySec,practice:pc+"/5",test:tc+"/3",pct:p,total});localStorage.setItem("eliseLearning",JSON.stringify(S));$("pct").textContent=p+"%";$("badge").textContent=p>=80?"🏆":p>=65?"👍":"🌱";$("message").textContent=p>=80?"Maîtrisé !":p>=65?"Réussi, à consolider.":"À retravailler : on reverra cette notion.";$("rTheory").textContent=fmt(theorySec);$("rPractice").textContent=pc+"/5";$("rTest").textContent=tc+"/3 ("+p+"%)";$("rTotal").textContent=fmt(total);show("result")}
function fmt(s){return Math.floor(s/60)+" min "+String(s%60).padStart(2,"0")+" s"}
function render(){$("xp").textContent="⭐ "+S.xp+" XP";$("streak").textContent=S.streak;$("sessions").textContent=S.sessions.length;$("pxp").textContent=S.xp;$("time").textContent=Math.round(S.sessions.reduce((a,b)=>a+b.total,0)/60)+" min";let x=S.sessions[0];$("last").innerHTML=x?`<b>${x.title}</b><div class="muted">${x.date}</div><div class="row"><span>Théorie</span><b>${fmt(x.theory)}</b></div><div class="row"><span>Exercices</span><b>${x.practice}</b></div><div class="row"><span>Test</span><b>${x.test} · ${x.pct}%</b></div><div class="row"><span>Total</span><b>${fmt(x.total)}</b></div>`:"Aucune séance."}
document.querySelectorAll("[data-start]").forEach(b=>b.onclick=()=>begin(b.dataset.start));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));$("back").onclick=()=>show("home");$("next").onclick=next;$("finish").onclick=()=>show("home");render();
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{});
