// Elise Learning V2.3 enhancements
rewards.splice(0,rewards.length,
{id:"screen15",icon:"🎮",name:"15 min de temps d'écran bonus",cost:300},
{id:"games20",icon:"🕹️",name:"20 min de jeux bonus",cost:350},
{id:"snap20",icon:"👻",name:"20 min de Snap bonus",cost:400},
{id:"dessert",icon:"🍰",name:"Un dessert au choix",cost:500},
{id:"lunch",icon:"🥪",name:"Bon : Papa prépare mon déjeuner d'école",cost:600},
{id:"snapSignup",icon:"📱",name:"Inscription à Snap · à partir de 13 ans",cost:1000,minAge:13}
);
const V23_RULES=`<div class="rulesBox"><h2>⭐ Règles des XP</h2><p>Les XP récompensent tes exercices, tes progrès et surtout ta régularité.</p><p><b>Gagner des XP</b><br>Chaque bonne réponse rapporte 10 XP. Un mini-test à 80 % ou plus donne 50 XP bonus.</p><p><b>Rester régulière</b><br>Après 3 jours complets sans exercice, ton solde diminue de 5 % par jour supplémentaire. La diminution totale est plafonnée à 20 % du solde du début de cette période d'inactivité.</p><p><b>Reprendre</b><br>Dès que tu termines une nouvelle séance, la période d'inactivité s'arrête. Les XP déjà retirés ne sont pas recrédités.</p><p><b>Récompenses</b><br>Tu peux échanger tes XP contre des privilèges personnels : temps d'écran, jeux, Snap, dessert ou un bon pour que Papa prépare ton déjeuner d'école. L'inscription à Snap coûte 1 000 XP et n'est disponible qu'à partir de 13 ans.</p><button class="primary" onclick="document.getElementById('xpRules').hidden=true">J'ai compris ✓</button></div>`;
function daysSince(isoDay){if(!isoDay)return 0;const a=new Date(isoDay+'T12:00:00'),b=new Date();b.setHours(12,0,0,0);return Math.max(0,Math.floor((b-a)/86400000));}
function applyInactivityPenalty(){if(!S.lastDay)return;const inactive=daysSince(S.lastDay);if(inactive<=3)return;const penaltyDays=Math.min(4,inactive-3),key=S.lastDay+':'+penaltyDays;if(S.penaltyKey===key)return;if(S.penaltyBaseDay!==S.lastDay){S.penaltyBaseDay=S.lastDay;S.penaltyBaseXp=Number(S.xp||0);}const target=Math.round(Number(S.penaltyBaseXp||0)*(1-0.05*penaltyDays));if(Number(S.xp||0)>target)S.xp=target;S.penaltyKey=key;localStorage.setItem('eliseLearningV2',JSON.stringify(S));if(typeof pushCloudState==='function')pushCloudState();}
// Only notify the parent when Elise actually starts an exercise session.
const v23Begin=begin;begin=function(k){v23Begin(k);report('Exercice commencé',`${lessons[k].title} · ${new Date().toLocaleString('fr-BE')}`);};
// Suppress automatic e-mail reports for completion and feedback; those events remain stored in the app/cloud.
const v23Report=report;report=async function(event,details){if(event==='Exercice commencé')return v23Report(event,details);};
const v23Done=done;done=function(){v23Done();if(currentRec)currentRec.version='V2.3';S.penaltyBaseDay=null;S.penaltyBaseXp=null;S.penaltyKey=null;save();};
const v23Render=render;render=function(){applyInactivityPenalty();v23Render();};
(function(){document.title='Elise Learning · V2.3';document.querySelectorAll('footer').forEach(x=>x.textContent='Elise Learning · V2.3');document.querySelectorAll('.pill').forEach(x=>{if(x.textContent.trim()==='V2.2')x.textContent='V2.3'});const xp=document.getElementById('xp');if(xp){xp.setAttribute('role','button');xp.setAttribute('tabindex','0');xp.title='Voir les règles XP';xp.onclick=()=>document.getElementById('xpRules').hidden=false;xp.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();xp.click();}};}const modal=document.createElement('div');modal.id='xpRules';modal.hidden=true;modal.className='rulesModal';modal.innerHTML=V23_RULES;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};document.body.appendChild(modal);const style=document.createElement('style');style.textContent='.pill[role=button]{cursor:pointer}.rulesModal{position:fixed;inset:0;background:#0008;z-index:1000;padding:18px;overflow:auto}.rulesModal[hidden]{display:none}.rulesBox{max-width:560px;margin:7vh auto;background:white;border-radius:22px;padding:22px;box-shadow:0 12px 50px #0004;line-height:1.5}.rulesBox h2{margin-top:0}';document.head.appendChild(style);applyInactivityPenalty();render();})();