import test from 'node:test';
import assert from 'node:assert/strict';
import {archiveMigration,restoreMigration} from '../v4/server/migration-archive.mjs';
import {FirestoreStore} from '../v4/server/store.mjs';
import {planMigration,applyMigration} from '../v4/server/migration.mjs';
test('large Unicode provenance archived privately under64KiB chunks and checksum detects corruption',()=>{const source={xp:615,evidence:'Élise 🏑 '.repeat(140000)},plan=planMigration(source),archive=archiveMigration(plan);assert.ok(Buffer.byteLength(JSON.stringify(plan))>1048576);assert.ok(archive.chunks.every(c=>Buffer.byteLength(JSON.stringify(c))<65536));assert.deepEqual(restoreMigration(archive.pointer,archive.chunks.reverse()),plan);assert.throws(()=>restoreMigration(archive.pointer,[]),/Incomplete/);const broken=structuredClone(archive.chunks);broken[0].data='AAAA';assert.throws(()=>restoreMigration(archive.pointer,broken),/checksum/);});
function fakeFirestore(){const docs=new Map();const ref=path=>({path,collection:name=>collection(`${path}/${name}`)}),collection=path=>({path,doc:id=>ref(`${path}/${id}`)});return {docs,collection,runTransaction:async fn=>{const writes=[];const result=await fn({get:async reference=>(assert.equal(writes.length,0,'Firestore reads must precede every write'),reference.collection?{exists:docs.has(reference.path),data:()=>structuredClone(docs.get(reference.path))}:{docs:[...docs].filter(([path])=>path.startsWith(reference.path+'/')&&path.split('/').length===reference.path.split('/').length+1).map(([path,data])=>({id:path.split('/').at(-1),data:()=>structuredClone(data)}))}),set:(reference,value)=>writes.push([reference.path,structuredClone(value)])});for(const [path,value]of writes)docs.set(path,value);return result;}};}
test('Firestore adapter archives large migration outside root and reapplies without loss or double credits',async()=>{const db=fakeFirestore(),store=new FirestoreStore(db),plan=planMigration({xp:615,evidence:'Élise 🏑 '.repeat(140000),sessions:[{id:'legacy1',pct:80,topicId:'be',subject:'english'}]});await store.transact('students/child',s=>applyMigration(s,plan,{backupVerified:true,identityVerified:true}));const root=db.docs.get('students/child');assert.ok(Buffer.byteLength(JSON.stringify(root))<10000);assert.equal(root.migration.archived,true);assert.equal(root.xp,615);const response=await store.transact('students/child',s=>{assert.deepEqual(s.migration.original,plan.original);return applyMigration(s,plan)});assert.deepEqual(response,{alreadyApplied:true});assert.equal(db.docs.get('students/child').xp,615);assert.equal(db.docs.get('students/child/history/legacy1').score,80);});
test('oversize archive capacity rejects before any mutation',async()=>{const db=fakeFirestore(),store=new FirestoreStore(db),plan=planMigration({xp:615,evidence:'x'.repeat(19_000_000)});await assert.rejects(()=>store.transact('students/child',s=>applyMigration(s,plan,{backupVerified:true,identityVerified:true})),/capacity/);assert.equal(db.docs.size,0);});

test('aggregate transaction bytes refuse otherwise valid chunks before any writes',async()=>{const db=fakeFirestore(),store=new FirestoreStore(db),plan=planMigration({xp:615,evidence:'x'.repeat(6_000_000)});assert.ok(archiveMigration(plan).chunks.length<400);await assert.rejects(()=>store.transact('students/child',s=>applyMigration(s,plan,{backupVerified:true,identityVerified:true})),/Transaction byte capacity/);assert.equal(db.docs.size,0);});
