import test from 'node:test';
import assert from 'node:assert/strict';
import {applyAction,initialState,day,penalty} from '../v4/core/engine.mjs';
const clock=Date.parse('2026-10-09T10:00:00Z');
const families=['recognise','complete','order','transform','produce'];
const catalogue=['english','math'].flatMap(subject=>Array.from({length:3},(_,n)=>({id:`${subject}-${n}`,subject,title:`${subject} chapter${n}`,theory:'A clear theory',questions:Array.from({length:180},(_,i)=>({id:`${subject}-${n}-${i}`,fingerprint:`${subject}-${n}-${i}`,family:families[i%5],prompt:`${subject} Q${n}/${i}`,type:'text',accepted:['correct'],explanation:'rule'}))})));
const run=(state,input,options={})=>applyAction(state,input,{catalogue,at:clock,...options});
function create(state,id='request',chapter='english-0',options={}){return run(state,{action:'create',chapterId:chapter,subject:chapter.split('-')[0],requestId:id},options)}
function complete(state,request='request',chapter='english-0',testCorrect=4,options={}){let s=create(state,request,chapter,options);run(state,{action:'practice',sessionId:s.id},options);for(let q of s.practice)run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'},options);s=run(state,{action:'startTest',sessionId:s.id},options);for(let [i,q]of s.test.entries())run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:i<testCorrect?'correct':'wrong'},options);return run(state,{action:'finish',sessionId:s.id},options)}
test('actual engine requires all practice and all mini-test answers',()=>{let state=initialState(),s=create(state);assert.throws(()=>run(state,{action:'startTest',sessionId:s.id}));run(state,{action:'practice',sessionId:s.id});for(let q of s.practice.slice(0,9))run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});assert.throws(()=>run(state,{action:'startTest',sessionId:s.id}));run(state,{action:'answer',sessionId:s.id,questionId:s.practice[9].id,answer:'correct'});s=run(state,{action:'startTest',sessionId:s.id});assert.throws(()=>run(state,{action:'finish',sessionId:s.id,practiceCorrect:10,testCorrect:5}));for(let q of s.test.slice(0,4))run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});assert.throws(()=>run(state,{action:'finish',sessionId:s.id}));assert.equal(state.xp,0);assert.equal(state.history.length,0)});
test('XP server corrected, client counts ignored, first answer immutable, finalization idempotent',()=>{let state=initialState();let s=complete(state,'a','english-0',4);assert.equal(state.xp,190);assert.equal(s.result.nextChapterId,'english-1');let snapshot=structuredClone(state);run(state,{action:'finish',sessionId:s.id,practiceCorrect:0,testCorrect:0});assert.deepEqual(state,snapshot);state=initialState();s=create(state);run(state,{action:'practice',sessionId:s.id});let q=s.practice[0];run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'wrong'});run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});assert.equal(state.sessions[s.id].answers[q.id].correct,false)});
test('test DTO protects corrected answers and refuses coach even client phase falsified',()=>{let state=initialState(),s=create(state);assert.ok(!('test'in s));run(state,{action:'practice',sessionId:s.id});for(let q of s.practice)run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});s=run(state,{action:'startTest',sessionId:s.id});assert.ok(!('theory'in s));for(let q of s.test){assert.ok(!('accepted'in q));assert.ok(!('correctIndex'in q));assert.ok(!('explanation'in q));}let q=s.test[0],r=run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});assert.ok(!('correct'in r));assert.ok(!('correct'in r.session.answers[q.id]));assert.throws(()=>run(state,{action:'help',sessionId:s.id,questionId:q.id,phase:'practice',mode:'qa'}));});
test('quality state projection unchanged and following normal earns full XP',()=>{let state=initialState(),baseline=structuredClone(state);let q=complete(state,'qa','english-0',5,{qa:true});assert.equal(q.result.earned,0);for(let k of ['xp','totalEarned','daily','history','ledger','progress','mastery','notifications','lastActivityDay'])assert.deepEqual(state[k],baseline[k]);complete(state,'normal','english-0',5);assert.equal(state.xp,200);assert.equal(state.history.length,1);assert.equal(state.notifications.length,2)});
test('six failed complete attempts block creation, no 400/half/third reward cap',()=>{let state=initialState();for(let n=0;n<6;n++)complete(state,'a'+n,'english-0',3);assert.equal(state.xp,780);assert.equal(state.daily['english:2026-10-09'].attempts,6);assert.throws(()=>create(state,'seventh'));assert.doesNotThrow(()=>create(state,'math','math-0'))});
test('three distinct passed chapters block, repeated chapter counted once',()=>{let state=initialState();complete(state,'a','english-0');complete(state,'b','english-0');complete(state,'c','english-1');assert.equal(state.daily['english:2026-10-09'].passed.length,2);complete(state,'d','english-2');assert.throws(()=>create(state,'e'));assert.equal(state.xp,760)});
test('abandon no quota and releases active slot, reusing create request returns same session',()=>{let state=initialState(),s=create(state,'a');assert.equal(create(state,'a').id,s.id);run(state,{action:'abandon',sessionId:s.id});assert.equal(state.xp,0);assert.equal(state.history.length,0);assert.equal(state.daily['english:2026-10-09'].attempts,0);assert.notEqual(create(state,'b').id,s.id);assert.throws(()=>run(state,{action:'finish',sessionId:s.id}));});
test('closes on Brussels midnight day including summer/winter dates',()=>{assert.equal(day(Date.parse('2026-03-29T22:00Z')),'2026-03-30');assert.equal(day(Date.parse('2026-10-25T23:00Z')),'2026-10-26');let state=initialState();complete(state,'a','english-0',4,{at:Date.parse('2026-10-09T22:01Z')});assert.equal(state.daily['english:2026-10-10'].attempts,1)});
test('inactivity 3 free calendar days then 5/10/15/20, bounded solde and no deferred debt',()=>{let state=initialState();state.xp=1000;state.lastActivityXP=1000;state.lastActivityDay='2026-10-01';for(let [date,xp]of [['2026-10-04',1000],['2026-10-05',950],['2026-10-06',900],['2026-10-07',850],['2026-10-08',800],['2026-10-25',800]]){penalty(state,Date.parse(date+'T12:00Z'));assert.equal(state.xp,xp)}state=initialState();state.xp=10;state.lastActivityXP=1000;state.lastActivityDay='2026-10-01';penalty(state,Date.parse('2026-10-05T12:00Z'));assert.equal(state.xp,0);state.xp=100;penalty(state,Date.parse('2026-10-05T13:00Z'));assert.equal(state.xp,100)});
test('locked chapter cannot be forged',()=>{assert.throws(()=>create(initialState(),'jump','english-2'));});
test('mini-test DTO also suppresses training theory and corrections, restores at balance',()=>{let state=initialState(),s=create(state);run(state,{action:'practice',sessionId:s.id});for(let q of s.practice)run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});s=run(state,{action:'startTest',sessionId:s.id});assert.deepEqual(s.practice,[]);assert.deepEqual(s.answers,{});assert.ok(!('theory'in s));for(let q of s.test)run(state,{action:'answer',sessionId:s.id,questionId:q.id,answer:'correct'});s=run(state,{action:'finish',sessionId:s.id});assert.equal(s.corrections.length,15);assert.equal(s.practice.length,10);});
