import test from 'node:test';
import assert from 'node:assert/strict';
import {englishChapters,generateEnglish} from '../v4/content/english.mjs';
import {mathChapters,generateMath} from '../v4/content/math.mjs';
import {applyAction,initialState,correct} from '../v4/core/engine.mjs';
const norm=x=>String(x).normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").trim().replace(/\s+/g,' ');
function check(chapters,generate,subject){assert.equal(chapters.length,subject==='english'?21:20);assert.equal(new Set(chapters.map(c=>c.id)).size,chapters.length);for(let c of chapters){assert.equal(c.families.length,5,c.id+' metadata five families');assert.ok(c.theoryHtml||c.theory,c.id+' theory');let avoid=[];for(let n=0;n<6;n++){let q=generate(c.id,{seed:'qa-independent-'+n,avoidFingerprints:avoid});if(q.practice)q=[...q.practice,...q.test];assert.equal(q.length,15,c.id+' 15 questions');assert.equal(new Set(q.map(x=>x.id)).size,15,c.id+' uniqueids');assert.equal(new Set(q.map(x=>norm(x.prompt))).size,15,c.id+' unique prompts');assert.equal(new Set(q.slice(0,10).map(x=>x.family)).size,5,c.id+' training families');assert.equal(new Set(q.slice(10).map(x=>x.family)).size,5,c.id+' test families');for(let x of q){assert.ok(x.explanation,c.id+' correctionexplains');assert.ok(x.fingerprint,c.id+' stable fingerprint');assert.ok(!avoid.includes(x.fingerprint),c.id+' 6 renewed attempts');if(x.options?.length){assert.equal(new Set(x.options.map(norm)).size,x.options.length,c.id+' distinctoptions');assert.ok(correct(x,x.options[x.correctIndex]),c.id+' rightchoiceaccepted');assert.equal(x.options.filter(o=>correct(x,o)).length,1,c.id+' singlecorrect');}else{assert.ok(x.accepted?.length,c.id+' accepted');assert.ok(correct(x,x.accepted[0]),c.id+' correcttextaccepted');}}avoid.push(...q.map(x=>x.fingerprint));}const catalogue=chapters.map(x=>({...x,subject,theory:x.theoryHtml??x.theory,generate:(seed,{previousFingerprints})=>generate(x.id,{seed,avoidFingerprints:previousFingerprints})}));let state=initialState();state.progress[subject]=chapters.length;assert.doesNotThrow(()=>applyAction(state,{action:'create',subject,chapterId:c.id,requestId:'test-'+c.id},{catalogue,at:Date.parse('2026-10-09T10:00Z')}),c.id+' actual server integration');}}
test('English21 chapters, five families, six renewed series, real engine compatibility',()=>check(englishChapters,generateEnglish,'english'));
test('English accepted negatives include contractions and apostrophe normalization',()=>{let all=[];for(let n=0;n<10;n++)all.push(...generateEnglish('be',{seed:'contractions'+n}));let negative=all.find(x=>x.accepted.some(a=>/is not/.test(a))&&['transform','produce'].includes(x.family));assert.ok(negative,'negative specimen');let contracted=negative.accepted.find(a=>/isn't/.test(a));assert.ok(contracted,'is not/isnt equivalent');assert.ok(correct(negative,contracted.replace("'",'’')));});

test('Math20 chapters, five families, six renewed series, real engine compatibility',()=>check(mathChapters,generateMath,'math'));
test('independent arithmetic oracle and unique mathematical divisible choices',()=>{let verified=0;for(let c of mathChapters)for(let n=0;n<10;n++)for(let q of generateMath(c.id,{seed:'oracle-'+n})){let match=q.prompt.match(/^Calcule (.+)\.$/);if(match&&!q.options){let expr=match[1].replace(/²/g,'**2').replace(/³/g,'**3').replace(/−/g,'-').replace(/×/g,'*').replace(/÷/g,'/');if(/^[\d.\s()+*/-]+$/.test(expr)){let value=Function('"use strict";return ('+expr+')')();let answer=Number(q.accepted[0].replace(',','.'));assert.ok(Math.abs(value-answer)<1e-7,q.prompt+' independently calculated');verified++;}}if(c.id==='divisibility'&&q.options){let multiple=q.prompt.match(/multiple de (\d+)/);let byfive=/divisible par 5/.test(q.prompt);let divisor=q.prompt.match(/divise (\d+) sans reste/);let valid=q.options.filter(x=>{let v=Number(x);return multiple?v%Number(multiple[1])===0:byfive?v%5===0:divisor?Number(divisor[1])%v===0:false});assert.equal(valid.length,1,q.prompt+' unique mathematical answer');assert.equal(valid[0],q.options[q.correctIndex]);}}assert.ok(verified>=100,'oracle covers at least100 arithmetic questions');});
test('English complete sentences optional terminal punctuation, grammar retained',()=>{let all=[];for(let n=0;n<10;n++)all.push(...generateEnglish('be',{seed:'optional-final-'+n}));let q=all.find(x=>['produce','transform'].includes(x.family)&&x.accepted[0].endsWith('.'));assert.ok(q);assert.ok(correct(q,q.accepted[0].slice(0,-1)));let wrong=q.accepted[0].replace(/\b(am|is|are)\b/,'wrongverb');assert.ok(!correct(q,wrong));});
