import test from 'node:test';
import assert from 'node:assert/strict';
import {planMigration,applyMigration} from '../v4/server/migration.mjs';
import {mathChapters} from '../v4/content/math.mjs';
import {initialState,applyAction} from '../v4/core/engine.mjs';
const source={xp:615,englishTopicV31:3,mathTopicV31:2,lastDay:'2026-10-08',sessions:[{id:123,subject:'english',topicId:'be',pct:80,xpEarned:190,localDay:'2026-10-08',answers:[{given:'She is ready',correct:true}]}],redemptions:[{name:'Screen15',cost:300}],unknownProof:'retained'};
test('actual legacy V3 sessions and progress preserved without recalculation, unknown provenance retained',()=>{let plan=planMigration(source),state=initialState();assert.equal(plan.history.length,1);assert.equal(plan.history[0].score,80);assert.equal(plan.history[0].earned,190);assert.equal(plan.history[0].chapterId,'be');assert.equal(plan.original.unknownProof,'retained');assert.equal(plan.redemptions.length,1);assert.throws(()=>applyMigration(state,plan));applyMigration(state,plan,{backupVerified:true,identityVerified:true});assert.equal(state.xp,615);assert.equal(state.history.length,1);assert.equal(state.progress.english,3);assert.equal(state.progress.math,2);let before=structuredClone(state);assert.deepEqual(applyMigration(state,plan,{backupVerified:true,identityVerified:true}),{alreadyApplied:true});assert.deepEqual(state,before);});
test('conflicting sources and nonempty targets rejected rather than maximum XP resurrection',()=>{assert.throws(()=>planMigration({...source,history:[]}));let s=initialState();s.xp=10;assert.throws(()=>applyMigration(s,planMigration(source),{backupVerified:true,identityVerified:true}));s=initialState();applyMigration(s,planMigration(source),{backupVerified:true,identityVerified:true});assert.throws(()=>applyMigration(s,planMigration({...source,xp:1000}),{backupVerified:true,identityVerified:true}));assert.equal(s.xp,615)});
test('malformed legacy inputs rejected, no invented history',()=>{for(let xp of [-1,NaN,Infinity,1.5])assert.throws(()=>planMigration({xp}));assert.throws(()=>planMigration({xp:0,sessions:{}}));let p=planMigration({xp:0});assert.deepEqual(p.history,[]);assert.throws(()=>planMigration({xp:0,sessions:[{id:'same'},{id:'same'}]}));assert.throws(()=>planMigration({xp:0,englishTopicV31:-1}));});
test('legacy activity must be valid calendar date, not merely regex',()=>{assert.throws(()=>planMigration({xp:0,lastDay:'2026-99-99'}));assert.throws(()=>planMigration({xp:0,lastDay:'2026-02-30'}));});

test('legacy ordinal chapter mapped by stable id into reordered maths catalogue',()=>{const catalogue=mathChapters.map(c=>({...c,subject:'math'}));let p=planMigration({xp:25,mathTopicV31:3},{catalogue});assert.equal(p.progress.math,catalogue.findIndex(c=>c.id==='fractions'));assert.notEqual(p.progress.math,3);});
test('legacy documented daily attempts and distinct passes preserve limits, QA excluded',()=>{let sessions=[{id:'a',subject:'english',topicId:'be',pct:80,localDay:'2026-10-09'},{id:'b',subject:'english',topicId:'be',pct:100,localDay:'2026-10-09'},{id:'c',subject:'english',topicId:'have',pct:60,localDay:'2026-10-09'},{id:'qa',subject:'english',topicId:'present',pct:100,localDay:'2026-10-09',testMode:true}];let plan=planMigration({xp:500,sessions}),state=initialState();applyMigration(state,plan,{backupVerified:true,identityVerified:true});assert.equal(state.daily['english:2026-10-09'].attempts,3);assert.deepEqual(state.daily['english:2026-10-09'].passed,['be']);assert.deepEqual(state.mastery.english,['be']);assert.equal(state.xp,500);});

test('legacy reward requests remain visible without replaying debit',()=>{let state=initialState();applyMigration(state,planMigration(source),{backupVerified:true,identityVerified:true});let d=applyAction(state,{action:'dashboard'},{catalogue:[],at:Date.parse('2026-10-09T10:00Z')});assert.equal(d.redemptions.length,1);assert.equal(d.redemptions[0].name,'Screen15');assert.equal(state.ledger.length,0);assert.equal(state.xp,615);});
test('migration rejects prior balances, progression, rewards or other-version provenance without overwriting evidence',()=>{const plan=planMigration(source);for(const setup of [s=>s.totalEarned=1,s=>s.progress.math=1,s=>s.rewardRequests.x={id:'x',status:'pending'},s=>s.notifications.push({id:'n'}),s=>s.migration={version:'older'},s=>s.mastery.math.push('fractions')]){const state=initialState();setup(state);const before=structuredClone(state);assert.throws(()=>applyMigration(state,plan,{backupVerified:true,identityVerified:true}),/not empty/);assert.deepEqual(state,before)}});
